# This is a basic workflow to help you get started with Actions

name: Pull Request to development build only

# Controls when the workflow will run
on:
  # Triggers the workflow on pull request events but only for the develop branch
  pull_request:
    branches: [ develop ]

  # Allows you to run this workflow manually from the Actions tab
  #workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Build and set up backend
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Analyze Code with pylint
        run: |
          find . -name '*.py' -exec pylint {} \;
      
      # Build and set up frontend
      - name: Set up Node 12.x
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Install dependencies
        working-directory: ./front-end/analytics-app
        run: npm install
      
      - name: Build Angular frontend
        working-directory: ./front-end/analytics-app
        run: yarn ng build --configuration production

      - name: Archive build
        if: success()
        uses: actions/upload-artifact@v1
        with:
          name: deploy_dist
          path: ./front-end/analytics-app/nginx-hosting/dist

  deploy:
    # Backend
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout develop
        uses: actions/checkout@v2
        working-directory: ./front-end/analytics-app/nginx-hosting

      - name: Deploy Backend to App Engine Develop
        uses: google-github-actions/deploy-appengine@v0.4.0
        working-directory: ./front-end/analytics-app/nginx-hosting
        with:
          project_id: ${{ secrets.GCP_PROJECT }}
          credentials: ${{ secrets.GCP_CREDENTIALS }}
          deliverables: app.yaml
          version: develop
          promote: false 

      - name: Download frontend build
        uses: actions/download-artifact@v1
        working-directory: ./front-end/analytics-app/nginx-hosting
        with:
          name: deploy_dist

      # Setup gcloud CLI
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        working-directory: ./front-end/analytics-app/nginx-hosting
        with:
          service_account_email: ${{ secrets.GCP_EMAIL }}
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}
          export_default_credentials: true
    
      # Configure Docker with Credentials
      - name: Configure Docker
        working-directory: ./front-end/analytics-app/nginx-hosting
        run: |
          gcloud auth configure-docker
      
      # Build the Docker image
      # gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT }}/${{ secrets.GCP_APPLICATION_DEV }}
      - name: Build & Publish
        working-directory: ./front-end/analytics-app/nginx-hosting
        run: |
          gcloud config set project ${{ secrets.GCP_PROJECT }}
          gcloud builds submit
      
      - name: Deploy Image to GAE
        working-directory: ./front-end/analytics-app/nginx-hosting
        run: |
          gcloud app deploy --image-url us.gcr.io/${{ secrets.GCP_PROJECT }}/${{ secrets.GCP_APPLICATION_DEV }}